# AI Personal Trainer - Streamlit Native (Snowflake) manifest
# Purpose: schema + deployment + integration settings for AI-generated workout & meal plans
# Stage 1: Personalized workout and meal plan generation using Cortex Prompt Complete

app:
  name: ai_personal_trainer_stage1
  description: >-
    AI-powered personal training app hosted in Snowflake (Streamlit Native).
    Stage 1 focuses on personalized workout and meal plan generation using Cortex Prompt Complete.
    Stores client profiles, generated workouts, meal plans/recipes, weigh-ins, and measurements.
  version: 0.1.0
  stage: 1
  features:
    - Automatic workout generation via Cortex Prompt Complete
    - Personalized meal plan generation
    - Client profile management
    - Weight tracking and body measurements

deployment:
  platform: snowflake_streamlit_native
  streamlit:
    entrypoint: app.py
    main_module: app.main
    requirements:
      - streamlit>=1.20
      - pandas
      - numpy
      - scikit-learn
      - sqlalchemy
      - snowflake-connector-python
      - snowflake-snowpark-python
    env_secrets:
      - SNOWFLAKE_ACCOUNT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_ROLE
      - SNOWFLAKE_WAREHOUSE
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_SCHEMA
    streamlit_settings:
      theme: light
      show_spinner: true
  
  streamlit_input_forms:
    description: "Forms for client profile and manual weigh-in data entry"
    
    client_profile_form:
      - label: "Client Name"
        field: client_name
        type: text_input
        required: true
      - label: "Age"
        field: age
        type: number_input
        min_value: 18
        max_value: 100
        required: true
      - label: "Gender"
        field: gender
        type: selectbox
        options: ["Male", "Female", "Other"]
        required: true
      - label: "Current Weight (kg)"
        field: current_weight_kg
        type: number_input
        format: "%.2f"
        required: true
      - label: "Height (cm)"
        field: height_cm
        type: number_input
        format: "%d"
        required: true
      - label: "Fitness Level"
        field: fitness_level
        type: selectbox
        options: ["Beginner", "Intermediate", "Advanced"]
        required: true
      - label: "Fitness Goals"
        field: fitness_goals
        type: multiselect
        options: ["Weight Loss", "Muscle Gain", "Endurance", "Strength", "General Fitness", "Flexibility"]
        required: true
      - label: "Available Equipment"
        field: available_equipment
        type: multiselect
        options: ["Dumbbells", "Barbell", "Gym Machine", "Cardio Equipment", "Bodyweight Only", "Resistance Bands"]
        required: true
      - label: "Days Available per Week"
        field: days_per_week
        type: number_input
        min_value: 1
        max_value: 7
        format: "%d"
        required: true
      - label: "Workout Duration (minutes)"
        field: workout_duration_min
        type: number_input
        min_value: 15
        max_value: 180
        format: "%d"
        required: true
      - label: "Dietary Preferences"
        field: dietary_preferences
        type: multiselect
        options: ["Vegetarian", "Vegan", "Keto", "Paleo", "Mediterranean", "None"]
        required: false
      - label: "Allergies / Restrictions"
        field: allergies
        type: text_area
        placeholder: "e.g., nuts, dairy, gluten"
        required: false
      - label: "Caloric Target (kcal/day)"
        field: target_calories
        type: number_input
        min_value: 1200
        max_value: 5000
        format: "%d"
        required: false
      - label: "Protein Target (g/day)"
        field: target_protein_g
        type: number_input
        min_value: 50
        max_value: 300
        format: "%d"
        required: false
    
    weigh_in_form:
      - label: "Date"
        field: weigh_in_date
        type: date_input
        required: true
      - label: "Weight (kg)"
        field: weight_kg
        type: number_input
        format: "%.2f"
        required: true
      - label: "Body Fat %"
        field: body_fat_pct
        type: number_input
        min_value: 5
        max_value: 50
        format: "%.1f"
        required: false
      - label: "Notes"
        field: notes
        type: text_area
        required: false
    
    body_measurements_form:
      - label: "Date"
        field: measurement_date
        type: date_input
        required: true
      - label: "Neck (cm)"
        field: neck_cm
        type: number_input
        format: "%.1f"
        required: false
      - label: "Chest (cm)"
        field: chest_cm
        type: number_input
        format: "%.1f"
        required: false
      - label: "Waist (cm)"
        field: waist_cm
        type: number_input
        format: "%.1f"
        required: false
      - label: "Hip (cm)"
        field: hip_cm
        type: number_input
        format: "%.1f"
        required: false
      - label: "Thigh (cm)"
        field: thigh_cm
        type: number_input
        format: "%.1f"
        required: false
      - label: "Calf (cm)"
        field: calf_cm
        type: number_input
        format: "%.1f"
        required: false

snowflake:
  account: ${SNOWFLAKE_ACCOUNT}
  user: ${SNOWFLAKE_USER}
  role: ${SNOWFLAKE_ROLE}
  warehouse: ${SNOWFLAKE_WAREHOUSE}
  database: ${SNOWFLAKE_DATABASE:TRAINING_DB}
  schema: ${SNOWFLAKE_SCHEMA:PUBLIC}
  objects:
    stages:
      - name: streamlit_app_stage
        type: internal
        directory_enabled: true
        comment: "Stage for Streamlit app files"
    file_formats:
      - name: json_format
        type: json

data_model:
  description: Snowflake table definitions for Stage 1 - Clients, Meal Plans, and Weight Tracking
  tables:
    clients:
      columns:
        client_id: {type: VARCHAR(36), pk: true, comment: "UUID"}
        client_name: {type: VARCHAR(100), nullable: false}
        age: {type: NUMBER(3,0), nullable: false}
        gender: {type: VARCHAR(20), nullable: false}
        current_weight_kg: {type: NUMBER(7,2), nullable: false}
        height_cm: {type: NUMBER(5,0), nullable: false}
        fitness_level: {type: VARCHAR(50), nullable: false, comment: "Beginner|Intermediate|Advanced"}
        fitness_goals: {type: VARIANT, nullable: false, comment: "JSON array of goals"}
        available_equipment: {type: VARIANT, nullable: false, comment: "JSON array of equipment"}
        days_per_week: {type: NUMBER(1,0), nullable: false, comment: "1-7 days"}
        workout_duration_min: {type: NUMBER(3,0), nullable: false, comment: "minutes per session"}
        dietary_preferences: {type: VARIANT, comment: "JSON array of preferences"}
        allergies: {type: VARCHAR(1000), comment: "Free-form allergies/restrictions"}
        target_calories: {type: NUMBER(5,0), comment: "daily caloric target"}
        target_protein_g: {type: NUMBER(5,0), comment: "daily protein target"}
        created_at: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP}
        updated_at: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP}
      comment: "Client profiles with fitness goals and preferences"

    weigh_ins:
      columns:
        weigh_in_id: {type: VARCHAR(36), pk: true}
        client_id: {type: VARCHAR(36), fk: clients.client_id, nullable: false}
        weigh_in_date: {type: DATE, nullable: false}
        weight_kg: {type: NUMBER(7,3), nullable: false}
        body_fat_pct: {type: NUMBER(5,2), comment: "Optional body fat percentage"}
        notes: {type: VARCHAR(500), comment: "Optional notes"}
        recorded_at: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP}
      comment: "Weight tracking for clients"

    body_measurements:
      columns:
        measurement_id: {type: VARCHAR(36), pk: true}
        client_id: {type: VARCHAR(36), fk: clients.client_id, nullable: false}
        measurement_date: {type: DATE, nullable: false}
        neck_cm: {type: NUMBER(6,2)}
        chest_cm: {type: NUMBER(6,2)}
        waist_cm: {type: NUMBER(6,2)}
        hip_cm: {type: NUMBER(6,2)}
        thigh_cm: {type: NUMBER(6,2)}
        calf_cm: {type: NUMBER(6,2)}
        recorded_at: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP}
      comment: "Body measurements over time"

    generated_workouts:
      columns:
        workout_id: {type: VARCHAR(36), pk: true}
        client_id: {type: VARCHAR(36), fk: clients.client_id, nullable: false}
        generation_date: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP, nullable: false}
        workout_week: {type: NUMBER(2,0), nullable: false, comment: "Week number in plan"}
        workout_day: {type: NUMBER(1,0), nullable: false, comment: "Day of week (1-7)"}
        workout_focus: {type: VARCHAR(200), nullable: false, comment: "e.g., 'Chest & Triceps', 'Leg Day'"}
        duration_min: {type: NUMBER(3,0), nullable: false}
        warm_up: {type: VARCHAR(1000), nullable: false}
        exercises: {type: VARIANT, nullable: false, comment: "JSON array of exercises with sets/reps"}
        cool_down: {type: VARCHAR(1000), nullable: false}
        notes: {type: VARCHAR(2000)}
        cortex_prompt: {type: VARCHAR(4000), comment: "Cortex Prompt Complete prompt used for generation"}
        cortex_model: {type: VARCHAR(100), default: 'mistral-7b', comment: "Model used for generation"}
      comment: "AI-generated workouts using Cortex Prompt Complete"

    meal_plans:
      columns:
        meal_plan_id: {type: VARCHAR(36), pk: true}
        client_id: {type: VARCHAR(36), fk: clients.client_id, nullable: false}
        generation_date: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP, nullable: false}
        plan_week: {type: NUMBER(2,0), nullable: false, comment: "Week number"}
        duration_days: {type: NUMBER(2,0), default: 7, comment: "Number of days in plan"}
        total_calories: {type: NUMBER(5,0), nullable: false}
        protein_g: {type: NUMBER(5,0), nullable: false}
        carbs_g: {type: NUMBER(5,0), nullable: false}
        fat_g: {type: NUMBER(5,0), nullable: false}
        meal_plan_json: {type: VARIANT, nullable: false, comment: "Complete meal plan with daily breakdowns"}
        cortex_prompt: {type: VARCHAR(4000), comment: "Cortex Prompt Complete prompt used for generation"}
        cortex_model: {type: VARCHAR(100), default: 'mistral-7b', comment: "Model used for generation"}
      comment: "AI-generated meal plans using Cortex Prompt Complete"

    recipes:
      columns:
        recipe_id: {type: VARCHAR(36), pk: true}
        recipe_name: {type: VARCHAR(300), nullable: false}
        servings: {type: NUMBER(2,0), nullable: false}
        total_calories: {type: NUMBER(5,0), nullable: false}
        protein_g: {type: NUMBER(5,1), nullable: false}
        carbs_g: {type: NUMBER(5,1), nullable: false}
        fat_g: {type: NUMBER(5,1), nullable: false}
        ingredients: {type: VARIANT, nullable: false, comment: "JSON array of ingredients"}
        instructions: {type: VARCHAR(4000), nullable: false}
        prep_time_min: {type: NUMBER(3,0)}
        cook_time_min: {type: NUMBER(3,0)}
        tags: {type: VARIANT, comment: "JSON array of tags (vegetarian, vegan, etc.)"}
        created_at: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP}
      comment: "Recipe library for meal plans"

    exercises_library:
      columns:
        exercise_id: {type: VARCHAR(36), pk: true}
        exercise_name: {type: VARCHAR(200), nullable: false}
        category: {type: VARCHAR(100), nullable: false, comment: "strength|cardio|flexibility"}
        target_muscles: {type: VARIANT, comment: "JSON array of muscle groups"}
        equipment_required: {type: VARIANT, comment: "JSON array of equipment"}
        difficulty_level: {type: VARCHAR(20), comment: "Beginner|Intermediate|Advanced"}
        instructions: {type: VARCHAR(2000)}
        variations: {type: VARIANT, comment: "JSON array of exercise variations"}
        created_at: {type: TIMESTAMP_LTZ, default: CURRENT_TIMESTAMP}
      comment: "Exercise reference library"

pipelines:
  cortex_generation:
    workout_generation:
      description: "Generate personalized workouts using Cortex Prompt Complete"
      trigger: "On-demand via Streamlit UI"
      method: CORTEX.COMPLETE()
      model: mistral-7b
      prompt_template: |
        You are an expert personal trainer. Generate a detailed workout plan for a client.
        
        Client Profile:
        - Fitness Level: {fitness_level}
        - Goals: {fitness_goals}
        - Available Equipment: {available_equipment}
        - Days Available per Week: {days_per_week}
        - Preferred Duration: {workout_duration_min} minutes
        
        Generate a complete {workout_duration_min}-minute workout including:
        1. Warm-up (5 minutes)
        2. Main exercises with sets, reps, and rest periods
        3. Cool-down (5-10 minutes)
        
        Format as JSON with structure:
        {{
          "warm_up": "description",
          "exercises": [
            {{"name": "exercise", "sets": X, "reps": "Y-Z", "rest_sec": 60, "notes": "cues"}},
            ...
          ],
          "cool_down": "description"
        }}
    
    meal_plan_generation:
      description: "Generate personalized meal plans using Cortex Prompt Complete"
      trigger: "On-demand via Streamlit UI"
      method: CORTEX.COMPLETE()
      model: mistral-7b
      prompt_template: |
        You are a sports nutritionist. Create a detailed 7-day meal plan for a client.
        
        Client Profile:
        - Target Daily Calories: {target_calories}
        - Target Protein: {target_protein_g}g
        - Dietary Preferences: {dietary_preferences}
        - Allergies/Restrictions: {allergies}
        - Fitness Goals: {fitness_goals}
        
        Generate a complete 7-day meal plan with:
        1. Daily breakdown (breakfast, lunch, dinner, snacks)
        2. Macronutrient targets
        3. Specific recipes or foods
        
        Format as JSON with structure:
        {{
          "weekly_totals": {{"calories": X, "protein": Y, "carbs": Z, "fat": W}},
          "days": [
            {{
              "day": 1,
              "meals": [
                {{"meal_type": "breakfast", "foods": [...], "calories": X, "protein": Y}}
              ]
            }}
          ]
        }}

ai_integration:
  cortex_models:
    - model: mistral-7b
      max_tokens: 2048
      temperature: 0.7
    - model: snowflake-arctic
      max_tokens: 2048
      temperature: 0.5
  
  generation_endpoints:
    - name: generate_workout
      method: CORTEX.COMPLETE()
      timeout_sec: 60
      caching: true
    
    - name: generate_meal_plan
      method: CORTEX.COMPLETE()
      timeout_sec: 60
      caching: true

security:
  recommended_roles:
    - TRAINING_APP_ROLE
    - TRAINING_APP_ADMIN
  grants:
    - role: TRAINING_APP_ROLE
      privileges:
        - USAGE: [warehouse, database, schema]
        - SELECT/INSERT/UPDATE: [all_tables]
    - role: TRAINING_APP_ADMIN
      privileges:
        - OWNERSHIP: [warehouse, database, schema]
        - ALL: [all_tables]

observability:
  logging:
    - destination: snowflake_table
      table: app_logs
      events: ["workout_generated", "meal_plan_generated", "client_created", "weigh_in_recorded"]
  
  metrics:
    - name: workouts_generated_daily
      query: |
        SELECT COUNT(*) as count FROM generated_workouts 
        WHERE DATE(generation_date) = CURRENT_DATE()
    
    - name: meal_plans_generated_daily
      query: |
        SELECT COUNT(*) as count FROM meal_plans 
        WHERE DATE(generation_date) = CURRENT_DATE()
    
    - name: active_clients
      query: |
        SELECT COUNT(DISTINCT client_id) as count FROM clients

streamlit_pages:
  description: "Streamlit app pages for Stage 1"
  pages:
    - name: home
      title: "Welcome"
      description: "App overview and client management"
      components:
        - New Client Profile Form
        - View All Clients
        - Client Statistics
    
    - name: workout_generator
      title: "Generate Workout"
      description: "AI-powered workout generation using Cortex Prompt Complete"
      components:
        - Select Client
        - Generate Workout Button
        - Display Generated Workout
        - Save to Database
        - View Workout History
    
    - name: meal_plan_generator
      title: "Generate Meal Plan"
      description: "AI-powered meal plan generation using Cortex Prompt Complete"
      components:
        - Select Client
        - Generate Meal Plan Button
        - Display Generated Meal Plan
        - Save to Database
        - View Meal Plan History
    
    - name: weight_tracking
      title: "Weight & Measurements"
      description: "Track weight and body measurements over time"
      components:
        - Select Client
        - Record Weight (weigh-in form)
        - Record Body Measurements (measurements form)
        - Display Weight History Chart
        - Display Progress Trends
    
    - name: client_profile
      title: "Client Profiles"
      description: "View and manage client profiles"
      components:
        - Client List
        - View Client Details
        - Edit Client Profile
        - Delete Client

notes_and_next_steps:
  stage_1_deliverables:
    - "✅ Client profile form for capturing fitness goals, preferences, and constraints"
    - "✅ Workout generation via Cortex Prompt Complete (automatic, AI-powered)"
    - "✅ Meal plan generation via Cortex Prompt Complete (automatic, AI-powered)"
    - "✅ Weight tracking with weigh-in form"
    - "✅ Body measurements tracking"
    - "✅ Database schema for clients, generated_workouts, meal_plans, recipes, weigh_ins, body_measurements, exercises_library"
    - "✅ Streamlit UI with 5 pages: Home, Workout Generator, Meal Plan Generator, Weight Tracking, Client Profiles"
  
  implementation_notes:
    - "Trainers table REMOVED - AI (Cortex) acts as the trainer"
    - "Workout logging REMOVED - will be added in Stage 2"
    - "All workouts generated automatically via Cortex Prompt Complete using mistral-7b or snowflake-arctic"
    - "All meal plans generated automatically via Cortex Prompt Complete"
    - "Cortex responses stored in VARIANT columns for flexibility"
    - "Manual weigh-in entry form for clients to track progress"
    - "Exercise library table for reference and future workout analysis"
  
  future_stages:
    - "Stage 2: Add workout logging and actual performance tracking"
    - "Stage 3: Add running/cardio tracking with auto-generation"
    - "Stage 4: Add nutrition logging and recipe recommendations"
    - "Stage 5: Add progress analytics and prediction models"
    - "Stage 6: Add progress photos and visual tracking"
  
  cortex_prompt_complete_setup:
    - "Ensure Cortex is enabled in your Snowflake account"
    - "Grant CORTEX_FUNCTIONS usage privilege to TRAINING_APP_ROLE"
    - "Use CORTEX.COMPLETE() function in Streamlit app to call AI models"
    - "Models available: mistral-7b, snowflake-arctic, llama2-7b, etc."
    - "All Cortex calls should include timeout handling (60 sec recommended)"
    - "Consider caching Cortex responses to avoid redundant API calls" 
